WIP File Tree API
Storj/java-libstorj pull request #11
Opened 2018-03-28 08:28 UTC by kaloyan-raev

Fixes #10

2018-03-28 18:20 UTC, TopperDEL commented
It is working so far!

But I would still propose to return a generic "Content"-object - that Can be either a file or a Folder. Havin a file-object with the property "isDirectory" feels wrong. But that is just my opinion and not a big deal.

What I also would suggest is to put the methods "getChildren" into another helper-object to seperate that logic from the base-storj-functions. So if we introduce a Kind of "StorjExtended"-class or "StorjDirectoryHelper" it would make it more clear what happens here. On constructing such an object, you could take the original storj-object as Parameter so you Can call the base-functions.
Can you follow me? I'm Feeling like I cannot express myself currently. :)

But for the Moment, this helps me alot developing my next-project, the StorjFS filesystem. :) Thank you!

2018-03-29 07:25 UTC, kaloyan-raev commented
One of the options I considered was indeed a higher level API that calls the current low level API. It's good that you share the same thoughts, so I will explore this direction in my next iteration today.

2018-03-29 07:27 UTC, TopperDEL commented
High Level API and Lov Level API - These were the words I was missing yesterday. :)

Yes, I would suggest that, too.

2018-03-29 10:32 UTC, kaloyan-raev commented
I've pushed the reworked API. Look at the `FileTreeExample` for usage.

2018-03-29 11:29 UTC, TopperDEL commented
Looks good! Will have a deeper look at it - but might not happen before easter. But the coding and structures Looks good. Thank you for your effort and help!

2018-04-02 14:06 UTC, TopperDEL commented on src/main/java/io/storj/libstorj/fs/Dir.java
> +    Dir(Entry entry) {
Both constructors Need to be public, as I cannot use them on my wrapper.

2018-04-02 14:07 UTC, TopperDEL requested changes
Both constructors of class Dir Need to be public - otherwise I cannot wrap them correctly.

2018-04-05 19:12 UTC, TopperDEL commented
We Need to buffer the entries, though. Maybe if you just load the bucket-Contents once until a Change-Operation is performed?

2018-04-22 19:07 UTC, TopperDEL commented
Seems I found an error - but I'm not completely sure (it's late and I'm tired :) ).

I have a bucket called "Filezilla2" with the following Content (exemplary):
"Filezilla2\Richtfest\Norah Jones\Come Away With Me\Painter Song.mp3"

If I move from Filezilla2 to Richtfest and should get the conent "Norah Jones" - I get "Norah Jones\Come Away With Me\" instead. So your logic seems to jump over one Directory-depth. Maybe you can reproduce that.

2018-10-30 10:40 UTC, RichardLitt commented
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!

2018-10-30 10:40 UTC, closed without merging